# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               DB-PHP
tagline:             'A PHP Database Composer Access Module'
description:         'A PHP Database Composer Access Module.'
url:                 https://g7mzr.github.io/db-php
baseurl:             https://g7mzr.github.io/db-php
#paginate:            5

# About/contact
author:
  name:              Sandy McNeil
  url:               https://github.com/g7mzr
  email:             g7mzrdev@gmail.com

# Custom vars
version:             0.5.0
